name: MPET regression test

on: [push, workflow_dispatch]

jobs:
  test:
    
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7","3.8","3.9","3.10"]
    defaults:
      run:
        shell: bash -l {0}
    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: mpet
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: base-mpet
        ref: ${{ github.base_ref }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: mpet-env

    - name: Install daetools via conda
      run: |
        conda activate mpet-env
        conda install -c conda-forge daetools python=${{ matrix.python-version }} pip

    - name: Install additional dependencies using mpet's setup.py
      run: |
        cd mpet
        pip install .[test]

    - name: Set up test for modified branch
      run: |
        cd mpet/bin
        rm -rf workdir
        mkdir workdir
        cd workdir

        cp ../run_tests.py .
        ln -s ../../mpet .
        ln -s ../../tests .

    - name: run tests for modified branch and get coverage
      run: |
        conda activate mpet-env
        cd mpet/bin/workdir
        coverage run --source=../../mpet/ run_tests.py --test_dir ./tests --output_dir ../../bin/workdir/modified > /dev/null

    - name: upload Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mpet/bin/workdir
        coveralls --service=github || : #Dont fret if if fails

    - name: Checks test results
      run: |
        cd mpet/tests
        pytest --baseDir=ref_outputs --modDir=../bin/workdir/modified compare_tests.py
